name: Build Custom RoundSync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Run via Docker
        run: |
          # 1. Rakit image docker dari Dockerfile
          docker build -t roundsync-builder .
          
          # 2. Jalankan container dan paksa masukkan variabelnya menggunakan flag -e
          docker run --rm \
            -e RCLONE_REPO="https://github.com/gulp79/rclone-extra.git" \
            -e RCLONE_BRANCH="master" \
            -e BUILD_NAME="RoundSync-Extra" \
            -v ${{ github.workspace }}/output:/host_mount/output \
            roundsync-builder
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RoundSync-Extra-APK
          path: output/RoundSync-Extra/*.apk
